Introduce recovery_failed callback
ruby-amqp/bunny pull request #666
Opened 2023-06-09 13:36 UTC by Schmitze333

It’s possible to specify the recovery_attempts option on the Bunny::Session. 
Hitting the recovery attempts limit without a successful recovery leads to a cleanup of connection, etc.
However, the client is not informed about this state and has no chance to react upon it.

This PR introduces a callback which is executed in exactly the above described situation enabling client code to react to a failed recovery process.

Relates to: https://github.com/ruby-amqp/bunny/issues/665

2023-06-09 14:29 UTC, michaelklishin requested changes
Thank you for taking the time co contribute.

"recovery_failed" to me suggests that this callback will be used for *every* unsuccessful recovery attempts. If that's not the case, we should rename it "recovery_attemtps_exhausted" or something that clearly suggests that this callable will be invoked only once
for a series for unsuccessful recovery attempts.

2023-06-09 15:27 UTC, Schmitze333 commented
Yeah, I agree. That name is much better!
I'll make the necessary changes.

2023-06-09 17:32 UTC, michaelklishin approved these changes

2023-06-09 17:33 UTC, merged

2023-06-09 17:33 UTC, michaelklishin commented
@Schmitze333 thank you for contributing to Bunny!

2023-06-12 07:22 UTC, Schmitze333 commented
I did not provide a Changelog entry. Will that happen on the release or shall I add one?

2023-06-12 07:23 UTC, michaelklishin commented
I update change log before every release if necessary. Don't worry about it.

2023-06-12 10:31 UTC, michaelklishin commented
[`2.22.0` is up](https://rubygems.org/gems/bunny) on rubygems.org.